version: '3.1'

services:
  app:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    ports:
      - 3200:3000
    environment:
      DB_URI: ${DB_URI}
    networks:
      - infra

networks:
  infra:
